# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00b4de4a082d4c10ce6e0129071c71f727ef67d1153383a95755864a78d63f6c034d4d2076b438f55bfb3b9a3ae608944f75354dd8e228c7eef741094510de99

test:
  secret_key_base: 7996c92010a154c205cfccfccd5efe28ce7867112d9aa8405e5847656e783feae9e7fb24c2216aa338b4c3fff08e8f7c73e85766b9e20ae96ee5421d5f2589da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
